// export const HOME = "/";
export const ADMIN = "/admin";
export const APPLICANT = "/applicant/:id";
export const INSCRICAO = "/inscricao";
export const LOGIN = "/login";
export const PROJECTS = "/projects";
export const REGISTER = "/register";
export const STUDENT_HOME = "/student-home";
export const TEACHER_HOME = "/teacher-home";
